# Generated by Django 2.1.3 on 2018-11-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_students_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sem',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
