# Generated by Django 2.1.3 on 2018-11-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_semester_1_semester_2_semester_3_semester_4_semester_5_semester_6_semester_7_semester_8'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
