# Generated by Django 2.1.3 on 2018-11-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultys',
            name='username',
            field=models.CharField(default='aag001', max_length=200),
        ),
        migrations.AddField(
            model_name='semester_1',
            name='professerr_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_2',
            name='professerr_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_3',
            name='professerr_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_4',
            name='professerr_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_5',
            name='professerr_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_6',
            name='professerr_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_7',
            name='professerr_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_8',
            name='professerr_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
    ]
