# Generated by Django 2.1.3 on 2018-11-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20181104_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_1',
            name='professerr_name',
            field=models.ForeignKey(default='aag001', on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
        migrations.AlterField(
            model_name='semester_2',
            name='professerr_name',
            field=models.ForeignKey(default='aag001', on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
        migrations.AlterField(
            model_name='semester_3',
            name='professerr_name',
            field=models.ForeignKey(default='aag001', on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
        migrations.AlterField(
            model_name='semester_4',
            name='professerr_name',
            field=models.ForeignKey(default='aag001', on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
        migrations.AlterField(
            model_name='semester_5',
            name='professerr_name',
            field=models.ForeignKey(default='aag001', on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
        migrations.AlterField(
            model_name='semester_6',
            name='professerr_name',
            field=models.ForeignKey(default='aag001', on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
        migrations.AlterField(
            model_name='semester_7',
            name='professerr_name',
            field=models.ForeignKey(default='aag001', on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
        migrations.AlterField(
            model_name='semester_8',
            name='professerr_name',
            field=models.ForeignKey(default='aag001', on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
    ]
