# Generated by Django 2.1.3 on 2018-11-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20181104_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultys',
            name='username',
        ),
    ]
