# Generated by Django 2.1.3 on 2018-11-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_facultys_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultys',
            name='username',
            field=models.CharField(default='aag001', max_length=200),
        ),
    ]
