# Generated by Django 2.1.3 on 2018-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_facultys_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultys',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facultys',
            name='username',
            field=models.CharField(default='aag001', max_length=200, unique=True),
        ),
    ]
