# Generated by Django 2.1.3 on 2018-11-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20181105_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_1',
            name='subject_code',
            field=models.CharField(max_length=201, unique=True),
        ),
    ]
