# Generated by Django 2.1.3 on 2018-11-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20181105_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester_1',
            old_name='professerr_name',
            new_name='section',
        ),
    ]
