# Generated by Django 2.1.3 on 2018-11-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20181105_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pro',
        ),
    ]
