# Generated by Django 2.1.3 on 2018-11-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20181105_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester_1',
            name='professerr_name',
        ),
    ]
