# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-05 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_semester_1_professerr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_1',
            name='professerr_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
    ]
