# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-05 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20181105_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester_1',
            old_name='professerr_name',
            new_name='professer_name',
        ),
    ]
