# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20181105_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_1',
            name='professer_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
    ]
