# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-05 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20181105_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_2',
            name='professer_name',
            field=models.OneToOneField(default='aag001', on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
    ]
