# Generated by Django 2.1.3 on 2018-11-06 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20181105_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_1',
            name='professer_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Facultys'),
        ),
    ]
