# Generated by Django 2.1.3 on 2018-11-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20181110_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_student_attendance',
            name='date',
            field=models.CharField(max_length=201),
        ),
        migrations.AlterField(
            model_name='add_student_attendance',
            name='student_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Students'),
        ),
    ]
