# Generated by Django 2.1.3 on 2018-11-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20181110_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester_1',
            name='section',
            field=models.CharField(default='cs', max_length=201, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester_2',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_3',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_4',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_5',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_6',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_7',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AddField(
            model_name='semester_8',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
        migrations.AlterField(
            model_name='add_student_attendance',
            name='student_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Students'),
        ),
    ]
